name: Run Flake Linting
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  fmt:
    runs-on: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Flake check
        run: nix fmt
  check:
    runs-on: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Flake check
        run: nix flake check
