# https://github.com/commitizen-tools/commitizen-action/blob/673655ac2d9dbb1b6773c3b6191f78d9b3d2e4fa/.github/workflows/bumpversion.yaml
name: Release

on:
  push:
    branches:
      # Only create releases for main or else releases will be very crowded
      - main

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: "Release version from version bump"
    # Allow for releases and pull requests
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: LATEST.md
          git_redirect_stderr: true
          push: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          body_path: "LATEST.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
